apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: learnostic-assistant-development-secrets-provider
  namespace: learnostic-assistant-development
spec:
  provider: aws
  secretObjects:
    - secretName: learnostic-assistant-development-secrets
      type: Opaque
      data:
        - objectName: "LEARNOSTIC_READONLY_DB_USERNAME"
          key: "LEARNOSTIC_READONLY_DB_USERNAME"
        - objectName: "LEARNOSTIC_READONLY_DB_PASSWORD"
          key: "LEARNOSTIC_READONLY_DB_PASSWORD"
        - objectName: "LANGFUSE_SECRET_KEY"
          key: "LANGFUSE_SECRET_KEY"
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "development/learnostic-gen/learnostic-assistant"
        objectType: "secretsmanager"
        jmesPath:
          - path: "LEARNOSTIC_READONLY_DB_USERNAME"
            objectAlias: "LEARNOSTIC_READONLY_DB_USERNAME"
          - path: "LEARNOSTIC_READONLY_DB_PASSWORD"
            objectAlias: "LEARNOSTIC_READONLY_DB_PASSWORD"
          - path: "LANGFUSE_SECRET_KEY"
            objectAlias: "LANGFUSE_SECRET_KEY"
